<a href="https://colab.research.google.com/github/Samruddhi9090/data_science_SE_A_17/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Create a 3x3 NumPy matrix, compute its determinant and inverse, and solve the system of linear equations 2x+3y=10 and 4x+5y=20 using NumPy. Then, present the determinant, the inverse matrix, and the solution to the linear equations.

## Create 3x3 Matrix

### Subtask:
Create a 3x3 square matrix using NumPy.


**Reasoning**:
First, I'll import the NumPy library as `np` and then create a 3x3 matrix with arbitrary integer values as instructed.



In [1]:
import numpy as np

matrix_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Created 3x3 matrix:")
print(matrix_3x3)

Created 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Compute Determinant

### Subtask:
Compute the determinant of the created 3x3 matrix.


**Reasoning**:
I need to compute the determinant of the `matrix_3x3` using `np.linalg.det()` as instructed, store it in `determinant_3x3`, and then print the result.



In [2]:
determinant_3x3 = np.linalg.det(matrix_3x3)
print("Determinant of the 3x3 matrix:")
print(determinant_3x3)

Determinant of the 3x3 matrix:
0.0


## Compute Inverse

### Subtask:
Compute the inverse of the 3x3 matrix.

#### Reasoning:
The determinant of `matrix_3x3` is 0.0, which means the matrix is singular and therefore does not have an inverse. To proceed with computing the inverse, we need a non-singular matrix. Let's create a new 3x3 matrix with a non-zero determinant.

Let's define a new 3x3 matrix that is invertible.

**Reasoning**:
Since the previously created matrix is singular (determinant is 0), I need to define a new 3x3 matrix that is invertible before attempting to compute its inverse. I will define a new matrix and then print it to confirm its structure.



In [3]:
matrix_3x3_invertible = np.array([
    [1, 2, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("Created an invertible 3x3 matrix:")
print(matrix_3x3_invertible)

Created an invertible 3x3 matrix:
[[1 2 0]
 [0 1 0]
 [0 0 1]]


**Reasoning**:
Now that we have an invertible 3x3 matrix, I will compute its inverse using `np.linalg.inv()` and store it in a variable, then print the inverse matrix.



In [4]:
inverse_matrix_3x3 = np.linalg.inv(matrix_3x3_invertible)
print("Inverse of the invertible 3x3 matrix:")
print(inverse_matrix_3x3)

Inverse of the invertible 3x3 matrix:
[[ 1. -2.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Solve Linear Equations

### Subtask:
Solve the system of linear equations 2x+3y=10 and 4x+5y=20 using NumPy.


**Reasoning**:
I need to define the coefficient matrix 'A' and the constant vector 'B' based on the given linear equations, then use `np.linalg.solve()` to find the solution and print it.



In [5]:
A = np.array([
    [2, 3],
    [4, 5]
])

B = np.array([10, 20])

solution_linear_equations = np.linalg.solve(A, B)

print("Solution to the system of linear equations:")
print(solution_linear_equations)

Solution to the system of linear equations:
[5. 0.]


## Final Task

### Subtask:
Present the determinant, inverse matrix, and the solution to the system of linear equations.


## Summary:

### Q&A
The determinant of the initial 3x3 matrix `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` is 0.0.
The inverse of the invertible 3x3 matrix `[[1, 2, 0], [0, 1, 0], [0, 0, 1]]` is `[[1., -2., 0.], [0., 1., 0.], [0., 0., 1.]]`.
The solution to the system of linear equations `2x + 3y = 10` and `4x + 5y = 20` is `x = 5` and `y = 0`.

### Data Analysis Key Findings
*   An initial 3x3 matrix was created: `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`.
*   The determinant of this initial 3x3 matrix was calculated to be 0.0, indicating it is a singular matrix and thus not invertible.
*   To demonstrate matrix inversion, a new invertible 3x3 matrix `[[1, 2, 0], [0, 1, 0], [0, 0, 1]]` was created.
*   The inverse of this new invertible matrix was successfully computed as `[[1., -2., 0.], [0., 1., 0.], [0., 0., 1.]]`.
*   The system of linear equations `2x + 3y = 10` and `4x + 5y = 20` was solved using NumPy, yielding the solution `x = 5` and `y = 0`.

### Insights or Next Steps
*   Understanding the determinant's role is crucial; a zero determinant implies a singular matrix, which has no inverse and means the system of equations it represents either has no solution or infinitely many solutions.
*   When dealing with real-world problems involving matrix inversion or solving linear systems, it's good practice to check the determinant of the matrix first to ensure a unique solution or a valid inverse exists.
